sudo: required
dist: trusty
language: node_js

env:
  matrix:
    - NODE_VERSION="8"
    - NODE_VERSION="9"
    - NODE_VERSION="10"
    - NODE_VERSION="11"
    - NODE_VERSION="12"

before_install:
  - pip install --user codecov
  # Prepare node and npm
  - nvm install $NODE_VERSION && nvm use $NODE_VERSION
  - npm install

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
  - npm run build
  - npm run check
  - npm test

after_success:
  - ./node_modules/.bin/codecov  -f coverage/coverage-final.json

addons:
  chrome: stable
  firefox: latest